### ISSUE TITLE
thanking

### ISSUE THREAD

**Issue by MarioMasta64** [shreydan/Anilist-Public-API-ID-query#1]
no issue to report, feel free to close

just wanted to thank you because i have been going insane trying to figure out how to check the next episode and the time left until one and this repo helped me finally understand it

thank you

**Comment by shreydan** [comment]
@MarioMasta64 thanks glad you found it helpful! I think their [API playground](https://anilist.co/graphiql) was really helpful to figure things out, check it out if you haven't!

**Comment by MarioMasta64** [comment]
no i found that its just that i kept reading about a different thing that didnt help me at all and kept erroring out

using the next airing episode example from here and merging it with what i have helped

also the playground doesnt help me unless im missing something it only shows info for 1 (cowboy bebop) so for things like currently releasing anime im unable to test other than putting it in my own code to test

**Comment by shreydan** [comment]
@MarioMasta64 ahh got it, when I was working on a project this API was bit painful to deal with for sure
